// Auto-generated by scripts/generate-skin-selectors.mjs — do not edit by hand.
// Sources: /Users/verger/code_source/front_end/important_project/oh-dsh-desktop-rebase/.cache/dsh-source/47f943859bef (apps/web/dist/assets + packages/*/*/lib/client.js)
//
// Each constant is the exact CSS Modules class list for one semantic
// geometry anchor of the ChatGPT skin (see CHATGPT_GEOMETRY_CSS).
// Regenerate after an upstream DSH bump: pnpm run generate:selectors
//
export const MENU_LIST = Object.freeze([
  '._list_19372_8',
  '._submenu_19372_9',
] as const)

export const MENU_SURFACE = Object.freeze([
  '.LqtciG_menu',
  '.gtvCtq_menu',
  '.vGKOra_menu',
  '.wI0qGa_menu',
] as const)

export const MENU_ITEM = Object.freeze([
  '._item_19372_91',
  '._item_1hk8w_28',
] as const)

export const ITEM_WRAP = Object.freeze([
  '._itemWrap_19372_91',
] as const)

export const ITEM_LABEL = Object.freeze([
  '._itemLabel_19372_173',
] as const)

export const NAV_CELL = Object.freeze([
  '.-wizCq_navCell',
] as const)

export const TRIGGER_PILL = Object.freeze([
  '.-wizCq_trigger',
  '.H3siGG_trigger',
  '.LqtciG_trigger',
  '.uNlE1G_trigger',
  '.vGKOra_trigger',
  '.vGKOra_triggerOpen',
  '.wI0qGa_trigger',
  '.wI0qGa_triggerDot',
  '.wI0qGa_triggerOpen',
] as const)

export const TRIGGER_LABEL = Object.freeze([
  '.-wizCq_triggerLabel',
  '.LqtciG_triggerLabel',
  '._0U89xG_triggerLabel',
  '.uNlE1G_triggerLabel',
] as const)

export const TRIGGER_EFFORT = Object.freeze([
  '.LqtciG_triggerEffort',
] as const)

export const TRIGGER_ICON = Object.freeze([
  '.uNlE1G_triggerIcon',
] as const)

export const SEAT = Object.freeze([
  '.urMWOG_seat',
] as const)

export const WORKSPACE_PILL = Object.freeze([
  '.N4HsDW_workspaceDropAfter',
  '.N4HsDW_workspaceDropBefore',
  '.UTNGfq_workspace',
  '.UTNGfq_workspaceRow',
] as const)

export const WORKSPACE_LABEL = Object.freeze([
  '.UTNGfq_workspaceLabel',
] as const)

export const GROUP_LABEL = Object.freeze([
  '._label_19372_123',
  '._label_4qrvp_95',
  '._label_biesw_32',
] as const)

export const SELECTOR = Object.freeze([
  '.AsQOla_selector',
  '.LGN8lq_selector',
  '._5HI2va_selector',
  '.sl_epq_selector',
] as const)

export const NEW_SESSION = Object.freeze([
  '.VfOgWa_newSession',
] as const)

export const SESSION_ROW = Object.freeze([
  '.Mxhjma_sessionRow',
] as const)

export const PROJECT_ROW = Object.freeze([
  '.Mxhjma_projectRow',
] as const)

export const WORKSPACE_ROW = Object.freeze([
  '.UTNGfq_workspaceRow',
] as const)

export const CARD = Object.freeze([
  '.EBSbfa_card',
  '.PWfTsa_card',
  '.PWfTsa_cardContent',
  '.PWfTsa_cardDetails',
  '.PWfTsa_cardTitle',
  '.PWfTsa_cardTrailing',
  '.PWfTsa_cards',
  '.QtPdFG_card',
  '.QtPdFG_cardOpen',
  '.TH6ClG_card',
  '._card_1b2ny_13',
  '._card_9gj4p_13',
  '.bWsSua_cards',
  '.fBOgmW_cardBody',
  '.kxQ7mG_card',
  '.lSocfq_card',
  '.lbz_ZG_card',
  '.lbz_ZG_cardWorkspaceTrigger',
  '.m2VMiW_card',
  '.naRqtq_card',
  '.uDZgaq_card',
  '.vI7wFG_card',
  '.z4NEJq_card',
  '.z4NEJq_cardActive',
  '.z4NEJq_cardBroken',
  '.z4NEJq_cardBrokenReason',
  '.z4NEJq_cardDesc',
  '.z4NEJq_cardFoot',
  '.z4NEJq_cardHead',
  '.z4NEJq_cardId',
  '.z4NEJq_cardMain',
  '.z4NEJq_cardName',
  '.z4NEJq_cards',
] as const)

export const DIALOG = Object.freeze([
  '._642HZG_dialog',
  '._dialog_15u5s_22',
  '.saFVAG_dialog',
  '.z4NEJq_dialog',
  '.z4NEJq_dialogFields',
] as const)

export const RENAME_INPUT = Object.freeze([
  '.Mxhjma_renameInput',
  '.N4HsDW_renameInput',
] as const)

export const THEME_CUBE = Object.freeze([
  '.OUwk0a_themeCube',
] as const)

export const PRIMARY_PILL = Object.freeze([
  '.IpZAPW_primary:not(._button_kz6gm_4)',
  '._2WqzUG_primaryButton:not(._button_kz6gm_4)',
  '._primary_kz6gm_38:not(._button_kz6gm_4)',
  '.lbz_ZG_primary:not(._button_kz6gm_4)',
] as const)

export const BUTTON_CLASS = Object.freeze([
  '._button_kz6gm_4',
] as const)

export const WRAP = Object.freeze([
  '._wrap_1ao1y_1',
  '._wrap_rcb0a_29',
  '.d5URwa_wrap',
] as const)

export const ICON = Object.freeze([
  '.EBSbfa_iconButton',
  '.Mxhjma_iconButton',
  '.N4HsDW_iconButton',
  '.OYLFnq_icon',
  '.TH6ClG_icon',
  '.VfOgWa_iconButton',
  '._2WqzUG_iconButton',
  '._2WqzUG_iconButtonDanger',
  '._64ccDW_iconBtn',
  '._iconIdle_9cl6j_42',
  '._icon_1ao1y_16',
  '._icon_fvpz7_35',
  '._icon_kz6gm_73',
  '.m2VMiW_iconIdle',
  '.vI7wFG_iconIdle',
  '.z4NEJq_iconButton',
  '.z4NEJq_iconDanger',
] as const)

export const BUTTON_MD = Object.freeze([
  '._button_kz6gm_4._md_kz6gm_24',
] as const)
