// Auto-generated by scripts/generate-skin-selectors.mjs — do not edit by hand.
// Sources: .cache/dsh-source/99f6f02fecdb (apps/web/dist/assets + packages/*/*/lib/client.js)
// DSH revision: 99f6f02fecdb
//
// Each constant is the exact CSS Modules class list for one semantic
// geometry anchor of the ChatGPT skin (see CHATGPT_GEOMETRY_CSS).
// Regenerate after an upstream DSH bump: pnpm run generate:selectors
//
export const MENU_LIST = Object.freeze([
  '._list_19372_8',
  '._submenu_19372_9',
] as const)

export const MENU_SURFACE = Object.freeze([
  '.HJg1BW_menu',
  '.IqNkMG_menu',
  '.YPFtDG_menu',
  '.Yfub0G_menu',
] as const)

export const MENU_ITEM = Object.freeze([
  '._item_19372_91',
  '._item_1hk8w_28',
] as const)

export const ITEM_WRAP = Object.freeze([
  '._itemWrap_19372_91',
] as const)

export const ITEM_LABEL = Object.freeze([
  '._itemLabel_19372_173',
] as const)

export const NAV_CELL = Object.freeze([
  '.xuwxfG_navCell',
] as const)

export const TRIGGER_PILL = Object.freeze([
  '.HJg1BW_trigger',
  '.HJg1BW_triggerOpen',
  '.IqNkMG_trigger',
  '.IqNkMG_triggerDot',
  '.IqNkMG_triggerOpen',
  '.YPFtDG_trigger',
  '.buGlmq_trigger',
  '.t3LyiG_trigger',
  '.xuwxfG_trigger',
] as const)

export const TRIGGER_LABEL = Object.freeze([
  '.YPFtDG_triggerLabel',
  '._84draq_triggerLabel',
  '.t3LyiG_triggerLabel',
  '.xuwxfG_triggerLabel',
] as const)

export const TRIGGER_EFFORT = Object.freeze([
  '.YPFtDG_triggerEffort',
] as const)

export const TRIGGER_ICON = Object.freeze([
  '.t3LyiG_triggerIcon',
] as const)

export const SEAT = Object.freeze([
  '._1Ig4fG_seat',
] as const)

export const WORKSPACE_PILL = Object.freeze([
  '.PtFn4G_workspaceDropAfter',
  '.PtFn4G_workspaceDropBefore',
  '.Qjtorq_workspace',
  '.Qjtorq_workspaceRow',
] as const)

export const WORKSPACE_LABEL = Object.freeze([
  '.Qjtorq_workspaceLabel',
] as const)

export const GROUP_LABEL = Object.freeze([
  '._label_19372_123',
  '._label_4qrvp_95',
  '._label_biesw_32',
] as const)

export const SELECTOR = Object.freeze([
  '.-NwZaq_selector',
  '.MWhFja_selector',
  '._0tHPRG_selector',
  '.aOgwKa_selector',
] as const)

export const NEW_SESSION = Object.freeze([
  '.m12uwa_newSession',
] as const)

export const SESSION_ROW = Object.freeze([
  '._6HNF1q_sessionRow',
] as const)

export const PROJECT_ROW = Object.freeze([
  '._6HNF1q_projectRow',
] as const)

export const WORKSPACE_ROW = Object.freeze([
  '.Qjtorq_workspaceRow',
] as const)

export const CARD = Object.freeze([
  '.APyKOW_card',
  '.B3yAbG_card',
  '.HiBPcq_card',
  '.HiBPcq_cardMinimized',
  '.KQbuAq_card',
  '.KQbuAq_cardWorkspaceTrigger',
  '.M0MgaG_card',
  '.MOz3Da_card',
  '._39TYyq_cardBody',
  '._3qhzW_card',
  '._card_1b2ny_13',
  '._card_9gj4p_13',
  '.kJAMVa_card',
  '.tKOGdG_card',
  '.tKOGdG_cardOpen',
  '.uPyePa_card',
  '.uPyePa_cardContent',
  '.uPyePa_cardDetails',
  '.uPyePa_cardTitle',
  '.uPyePa_cardTrailing',
  '.uPyePa_cards',
  '.vgQb0a_cards',
  '.xEma8G_card',
  '.y3Vqqq_card',
  '.y3Vqqq_cardActive',
  '.y3Vqqq_cardBroken',
  '.y3Vqqq_cardBrokenReason',
  '.y3Vqqq_cardDesc',
  '.y3Vqqq_cardFoot',
  '.y3Vqqq_cardHead',
  '.y3Vqqq_cardId',
  '.y3Vqqq_cardMain',
  '.y3Vqqq_cardName',
  '.y3Vqqq_cards',
] as const)

export const DIALOG = Object.freeze([
  '._dialog_15u5s_22',
  '.jhjh5G_dialog',
  '.k_1M_a_dialog',
  '.y3Vqqq_dialog',
  '.y3Vqqq_dialogFields',
] as const)

export const RENAME_INPUT = Object.freeze([
  '.PtFn4G_renameInput',
  '._6HNF1q_renameInput',
] as const)

export const THEME_CUBE = Object.freeze([
  '.fFsB5a_themeCube',
] as const)

export const PRIMARY_PILL = Object.freeze([
  '.KQbuAq_primary:not(._button_kz6gm_4)',
  '.Uk3LBG_primary:not(._button_kz6gm_4)',
  '._primary_kz6gm_38:not(._button_kz6gm_4)',
  '.flBquW_primaryButton:not(._button_kz6gm_4)',
] as const)

export const BUTTON_CLASS = Object.freeze([
  '._button_kz6gm_4',
] as const)

export const WRAP = Object.freeze([
  '._wrap_1ao1y_1',
  '._wrap_rcb0a_29',
  '.uQKy2W_wrap',
] as const)

export const ICON = Object.freeze([
  '.B3yAbG_iconIdle',
  '.HiBPcq_iconButton',
  '.M0MgaG_iconIdle',
  '.PtFn4G_iconButton',
  '._1mVAbq_iconBtn',
  '._6HNF1q_iconButton',
  '._iconIdle_9cl6j_42',
  '._icon_1ao1y_16',
  '._icon_fvpz7_35',
  '._icon_kz6gm_73',
  '.flBquW_iconButton',
  '.flBquW_iconButtonDanger',
  '.jW-jiW_icon',
  '.kJAMVa_icon',
  '.m12uwa_iconButton',
  '.y3Vqqq_iconButton',
  '.y3Vqqq_iconDanger',
] as const)

export const BUTTON_MD = Object.freeze([
  '._button_kz6gm_4._md_kz6gm_24',
] as const)

// leaf-4.3 C24: 组件级哈希选择器迁入生成输入清单（scripts/generate-skin-selectors.mjs
// ANCHORS 末尾），pnpm run generate:selectors 在上游 bump 后重钉。当前值与
// CHATGPT_GEOMETRY_CSS 的使用处一一对应。
export const CLOSE_BUTTON = Object.freeze([
  '._close_18d3q_30',
] as const)

export const REMOVE_BUTTON = Object.freeze([
  '._remove_1hk8w_53',
] as const)

export const ARROW_BUTTON = Object.freeze([
  '._arrow_1hk8w_90',
] as const)

export const FILTER_PILL = Object.freeze([
  '._pill_e3ygd_1',
] as const)

export const TOAST = Object.freeze([
  '._toast_fvpz7_7',
] as const)

export const ONBOARDING_MASK = Object.freeze([
  '._onboardingMask_1cfrq_10',
] as const)

export const RAIL = Object.freeze([
  '.xuwxfG_rail',
] as const)
