// Auto-generated by scripts/generate-skin-selectors.mjs — do not edit by hand.
// Sources: /Users/verger/code_source/front_end/important_project/oh-dsh-desktop-rebase/.cache/dsh-source/47f943859bef (apps/web/dist/assets + packages/*/*/lib/client.js)
//
// Each constant is the exact CSS Modules class list for one semantic
// geometry anchor of the ChatGPT skin (see CHATGPT_GEOMETRY_CSS).
// Regenerate after an upstream DSH bump: pnpm run generate:selectors
//
export const MENU_LIST = Object.freeze([
  '._list_19372_8',
  '._submenu_19372_9',
] as const)

export const MENU_SURFACE = Object.freeze([
  '.SLJQ8q_menu',
  '.Xflt8a_menu',
  '._273omW_menu',
  '._6JUrJq_menu',
] as const)

export const MENU_ITEM = Object.freeze([
  '._item_19372_91',
  '._item_1hk8w_28',
] as const)

export const ITEM_WRAP = Object.freeze([
  '._itemWrap_19372_91',
] as const)

export const ITEM_LABEL = Object.freeze([
  '._itemLabel_19372_173',
] as const)

export const NAV_CELL = Object.freeze([
  '._5J5IwG_navCell',
] as const)

export const TRIGGER_PILL = Object.freeze([
  '.RXWBNW_trigger',
  '.SLJQ8q_trigger',
  '._273omW_trigger',
  '._273omW_triggerOpen',
  '._5J5IwG_trigger',
  '._6JUrJq_trigger',
  '._6JUrJq_triggerDot',
  '._6JUrJq_triggerOpen',
  '.oevV-W_trigger',
] as const)

export const TRIGGER_LABEL = Object.freeze([
  '.Hfb7ua_triggerLabel',
  '.RXWBNW_triggerLabel',
  '.SLJQ8q_triggerLabel',
  '._5J5IwG_triggerLabel',
] as const)

export const TRIGGER_EFFORT = Object.freeze([
  '.SLJQ8q_triggerEffort',
] as const)

export const TRIGGER_ICON = Object.freeze([
  '.RXWBNW_triggerIcon',
] as const)

export const SEAT = Object.freeze([
  '.-nlEuW_seat',
] as const)

export const WORKSPACE_PILL = Object.freeze([
  '.-FzMdG_workspaceDropAfter',
  '.-FzMdG_workspaceDropBefore',
  '._045r0W_workspace',
  '._045r0W_workspaceRow',
] as const)

export const WORKSPACE_LABEL = Object.freeze([
  '._045r0W_workspaceLabel',
] as const)

export const GROUP_LABEL = Object.freeze([
  '._label_19372_123',
  '._label_4qrvp_95',
  '._label_biesw_32',
] as const)

export const SELECTOR = Object.freeze([
  '.G33h5a_selector',
  '._2TSIga_selector',
  '._2vQ3uG_selector',
  '._44MkdW_selector',
] as const)

export const NEW_SESSION = Object.freeze([
  '.XRFJpq_newSession',
] as const)

export const SESSION_ROW = Object.freeze([
  '.E6U8KW_sessionRow',
] as const)

export const PROJECT_ROW = Object.freeze([
  '.E6U8KW_projectRow',
] as const)

export const WORKSPACE_ROW = Object.freeze([
  '._045r0W_workspaceRow',
] as const)

export const CARD = Object.freeze([
  '.-RKVaW_card',
  '.AJMdJG_card',
  '.AJMdJG_cardContent',
  '.AJMdJG_cardDetails',
  '.AJMdJG_cardTitle',
  '.AJMdJG_cardTrailing',
  '.AJMdJG_cards',
  '.GJ_hHq_card',
  '.JyUsPW_card',
  '.JyUsPW_cardOpen',
  '.KyDztq_cardBody',
  '.Pf2xyW_cards',
  '.UdNE0q_card',
  '.UdNE0q_cardActive',
  '.UdNE0q_cardBroken',
  '.UdNE0q_cardBrokenReason',
  '.UdNE0q_cardDesc',
  '.UdNE0q_cardFoot',
  '.UdNE0q_cardHead',
  '.UdNE0q_cardId',
  '.UdNE0q_cardMain',
  '.UdNE0q_cardName',
  '.UdNE0q_cards',
  '._28FJ6W_card',
  '._3lgNhq_card',
  '._4wDhyG_card',
  '._card_1b2ny_13',
  '._card_9gj4p_13',
  '.l33V-W_card',
  '.ySYjtW_card',
  '.ystR2a_card',
  '.ystR2a_cardWorkspaceTrigger',
] as const)

export const DIALOG = Object.freeze([
  '.OTqlpa_dialog',
  '.UdNE0q_dialog',
  '.UdNE0q_dialogFields',
  '._dialog_15u5s_22',
  '.sieH7G_dialog',
] as const)

export const RENAME_INPUT = Object.freeze([
  '.-FzMdG_renameInput',
  '.E6U8KW_renameInput',
] as const)

export const THEME_CUBE = Object.freeze([
  '.Ol_1rG_themeCube',
] as const)

export const PRIMARY_PILL = Object.freeze([
  '.BSJ_qa_primaryButton:not(._button_kz6gm_4)',
  '._primary_kz6gm_38:not(._button_kz6gm_4)',
  '.omc2ra_primary:not(._button_kz6gm_4)',
  '.ystR2a_primary:not(._button_kz6gm_4)',
] as const)

export const BUTTON_CLASS = Object.freeze([
  '._button_kz6gm_4',
] as const)

export const WRAP = Object.freeze([
  '.ByE5Lq_wrap',
  '._wrap_1ao1y_1',
  '._wrap_rcb0a_29',
] as const)

export const ICON = Object.freeze([
  '.-FzMdG_iconButton',
  '.BSJ_qa_iconButton',
  '.BSJ_qa_iconButtonDanger',
  '.E6U8KW_iconButton',
  '.UdNE0q_iconButton',
  '.UdNE0q_iconDanger',
  '.XRFJpq_iconButton',
  '._0VrW4q_iconBtn',
  '._28FJ6W_iconButton',
  '._4wDhyG_iconIdle',
  '._5qFjmq_icon',
  '._iconIdle_9cl6j_42',
  '._icon_1ao1y_16',
  '._icon_fvpz7_35',
  '._icon_kz6gm_73',
  '.ySYjtW_icon',
] as const)

export const BUTTON_MD = Object.freeze([
  '._button_kz6gm_4._md_kz6gm_24',
] as const)
