/**
 * Generated by scripts/plugin-styles.mjs — do not edit by hand.
 * Per-file renamed class maps + merged scoped stylesheet for the forked
 * official CSS (lightningcss CSS Modules: per-file content-hash scoping so
 * same-named classes never collide; nesting flattened by the engine).
 */
export const SkinPickerCss = {
  "dsh-studio-skin-option": 'ohlr-kJfoja-dsh-studio-skin-option',
  "dsh-studio-skin-option-copy": 'ohlr-kJfoja-dsh-studio-skin-option-copy',
  "dsh-studio-skin-option-mode": 'ohlr-kJfoja-dsh-studio-skin-option-mode',
  "dsh-studio-skin-option-name": 'ohlr-kJfoja-dsh-studio-skin-option-name',
  "dsh-studio-skin-option-swatch": 'ohlr-kJfoja-dsh-studio-skin-option-swatch',
  "dsh-studio-skin-picker": 'ohlr-kJfoja-dsh-studio-skin-picker',
  "dsh-studio-skin-settings-row": 'ohlr-kJfoja-dsh-studio-skin-settings-row',
} as const

export const pluginCss = "/* skin-picker.module.css */\n.ohlr-kJfoja-dsh-studio-skin-settings-row .dsh-studio-ui-settings-row-layout {\n  align-items: stretch;\n  gap: var(--dsh-studio-space-3, 12px);\n  flex-direction: column;\n}\n\n.ohlr-kJfoja-dsh-studio-skin-settings-row .dsh-studio-ui-settings-row-control {\n  align-self: stretch;\n  display: block;\n}\n\n.ohlr-kJfoja-dsh-studio-skin-picker {\n  gap: var(--dsh-studio-space-2, 8px);\n  flex-wrap: wrap;\n  display: flex;\n}\n\n.ohlr-kJfoja-dsh-studio-skin-option {\n  align-items: center;\n  gap: 6px;\n  display: inline-flex !important;\n}\n\n.ohlr-kJfoja-dsh-studio-skin-option-swatch {\n  background: var(--dsh-studio-skin-accent);\n  border-radius: 999px;\n  flex: none;\n  width: 8px;\n  height: 8px;\n}\n\n.ohlr-kJfoja-dsh-studio-skin-option-copy {\n  align-items: baseline;\n  gap: 6px;\n  min-width: 0;\n  display: inline-flex;\n}\n\n.ohlr-kJfoja-dsh-studio-skin-option-name {\n  font-weight: 600;\n}\n\n.ohlr-kJfoja-dsh-studio-skin-option-mode {\n  color: var(--dsw-alias-label-tertiary, #8c959f);\n}\n\n"
