import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Interpreter variables with global semantics: every Electron binary honors
 * them regardless of who spawned it. They may exist only inside an exec
 * boundary (the spawn environment of our own interpreter launch) — never in
 * an inherited command environment. This list drives the generated scrub
 * module and its behavioral test; extend it only with the same care.
 */
export const DESKTOP_INTERPRETER_ENV_KEYS: readonly string[] = [
  'ELECTRON_RUN_AS_NODE',
]

const SCRUB_MODULE_NAME = 'dsh-studio-env-scrub.cjs'

/**
 * The scrub module is a regenerable artifact, so it lives under a `cache/`
 * sibling of the data root rather than the root itself (M10). Cleanup policy:
 * it is safe to delete at any time — `ensureEnvScrubModule` regenerates it
 * on the next desktop start whenever the source or the target differs.
 */
const SCRUB_CACHE_DIR = 'cache'

/**
 * Generated CommonJS source for the supervisor preload. Deleting a key from
 * `process.env` performs a real `unsetenv`, so descendants of this process
 * stop inheriting the variable while the interpreter itself already booted
 * with it — the variable ends up bound to its exec boundary.
 */
export function envScrubModuleSource(): string {
  const deletes = DESKTOP_INTERPRETER_ENV_KEYS
    .map(key => `\tdelete process.env[${JSON.stringify(key)}];`)
    .join('\n')
  return [
    '// Generated by DSH Studio: strip desktop interpreter plumbing from this',
    '// process environment so bundled runtime descendants inherit only the',
    '// user environment plus namespaced DSH_* variables. The interpreter',
    '// already consumed the variable at exec time; deleting it here is what',
    '// binds it to that boundary. Rewritten on desktop start; safe to delete.',
    'try {',
    deletes,
    '} catch {}',
    '',
  ].join('\n')
}

/**
 * Ensure the scrub module exists under the desktop data root and return its
 * absolute path, or null when it cannot be provided — the runtime launch then
 * degrades to the legacy inherited-variable behavior instead of failing.
 */
export function ensureEnvScrubModule(appDataPath: string): string | null {
  const modulePath = join(appDataPath, SCRUB_CACHE_DIR, SCRUB_MODULE_NAME)
  try {
    mkdirSync(join(appDataPath, SCRUB_CACHE_DIR), { recursive: true })
    const expected = envScrubModuleSource()
    let current: string | null = null
    try {
      current = readFileSync(modulePath, 'utf8')
    } catch {
      current = null
    }
    if (current !== expected) writeFileSync(modulePath, expected)
    return modulePath
  } catch {
    return null
  }
}
